spring:
  application:
    name: championship
  sleuth:
    sampler:
     probability: 1.0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true